[tool.poetry]
name = "mimesis"
version = "5.0.0"
description = "Mimesis: fake data generator."
authors = ["Isaak Uchakaev <likid.geimfari@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
codecov = "^2.1"
pytest = "^6.2"
pytest-isort = "^1.3.0"
pytest-cov = "^2.11"
pytest-mock = "^3.5"
requests = "^2.25"
mypy = "^0.910"
colorama = "^0.4.4"
pyroma = "^3.2"
pygments = "^2.8"
pytest-randomly = "^3.5"
check-manifest = "^0.46"
readme-renderer = "^29.0"
pytz = "^2021.1"
black = "^20.8b1"
autoflake = "^1.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
